/**
 * OpenAI Function Calling Target
 *
 * Generates tool definitions in the OpenAI Chat Completions API format.
 * Output: JSON array of function tool objects for the `tools` parameter.
 *
 * Format: { type: "function", function: { name, description, parameters, strict } }
 */

import type { AnvilTarget, AnvilTargetFactory } from '@anvil-tools/compiler';
import type { AnvilIR } from '@anvil-tools/schema';
import { toolParametersToJsonSchema } from '@anvil-tools/schema';

export interface OpenAITargetOptions {
  /** Enable strict mode (structured outputs) */
  strict?: boolean;
}

export const openai: AnvilTargetFactory<OpenAITargetOptions> = (options = {}) => ({
  name: 'openai',
  description: 'Generate OpenAI function calling tool definitions',
  primaryExtension: '.json',

  async generate(ir: AnvilIR) {
    const tools = ir.tools.map(tool => {
      const parameters = toolParametersToJsonSchema(tool);

      // OpenAI strict mode requires additionalProperties: false
      if (options.strict) {
        parameters['additionalProperties'] = false;
      }

      return {
        type: 'function' as const,
        function: {
          name: tool.name,
          description: tool.agent_description,
          parameters,
          ...(options.strict ? { strict: true } : {}),
        },
      };
    });

    const tsContent = `/**
 * OpenAI Chat Completions API tool definitions
 * Generated by Anvil v${ir.meta.anvil_version}
 *
 * Usage:
 *   import OpenAI from 'openai';
 *   import { tools } from './tools.js';
 *
 *   const client = new OpenAI();
 *   const response = await client.chat.completions.create({
 *     model: 'gpt-4o',
 *     tools,
 *     messages: [{ role: 'user', content: '...' }],
 *   });
 */

import type OpenAI from 'openai';

export const tools: OpenAI.Chat.Completions.ChatCompletionTool[] = ${JSON.stringify(tools, null, 2)};
`;

    return {
      target: 'openai',
      files: [
        { path: 'tools.json', content: JSON.stringify(tools, null, 2), type: 'schema' as const },
        { path: 'tools.ts', content: tsContent, type: 'source' as const },
      ],
    };
  },
});
