/**
 * TypeScript SDK Generator
 *
 * Generates a fully typed client SDK from Anvil IR.
 * Output includes:
 *   - TypeScript types for all tool inputs/outputs
 *   - A client class with methods for each tool
 *   - Zod schemas for runtime validation
 *   - Barrel export index
 */

import type { AnvilIR, AnvilIRTool, AnvilField } from '@anvil-tools/schema';
import type { TargetResult, GeneratedFile } from '@anvil-tools/compiler';

export interface SdkTsOptions {
  runtime?: 'fetch' | 'node';
}

export function generateSdkTs(ir: AnvilIR, options: SdkTsOptions = {}): TargetResult {
  const files: GeneratedFile[] = [];

  files.push({
    path: 'types.ts',
    content: generateTypes(ir),
    type: 'source',
  });

  files.push({
    path: 'schemas.ts',
    content: generateSchemas(ir),
    type: 'source',
  });

  files.push({
    path: 'client.ts',
    content: generateClient(ir, options),
    type: 'source',
  });

  files.push({
    path: 'index.ts',
    content: `export * from './types.js';\nexport * from './schemas.js';\nexport { ${pascalCase(ir.service.name)}Client } from './client.js';\n`,
    type: 'source',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: `${ir.service.name}-sdk`,
      version: ir.service.version,
      description: `TypeScript SDK for ${ir.service.name} — generated by Anvil`,
      type: 'module',
      main: './dist/index.js',
      types: './dist/index.d.ts',
      scripts: { build: 'tsc' },
      dependencies: { zod: '^3.24.0' },
      devDependencies: { typescript: '^5.8.0' },
    }, null, 2),
    type: 'config',
  });

  return { target: 'sdk-ts', files };
}

function generateTypes(ir: AnvilIR): string {
  const lines: string[] = [
    `/**`,
    ` * TypeScript types for ${ir.service.name}`,
    ` * Generated by Anvil v${ir.meta.anvil_version}`,
    ` */`,
    '',
  ];

  for (const tool of ir.tools) {
    const inputName = pascalCase(tool.name) + 'Input';
    const outputName = pascalCase(tool.name) + 'Output';

    lines.push(`export interface ${inputName} {`);
    for (const param of tool.parameters) {
      const opt = param.required ? '' : '?';
      const doc = param.field.description ? `  /** ${param.field.description} */\n` : '';
      lines.push(`${doc}  ${param.name}${opt}: ${tsFieldType(param.field)};`);
    }
    lines.push('}');
    lines.push('');

    if (tool.returns) {
      lines.push(`export interface ${outputName} ${tsObjectType(tool.returns)}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generateSchemas(ir: AnvilIR): string {
  const lines: string[] = [
    `/**`,
    ` * Zod schemas for runtime validation`,
    ` * Generated by Anvil v${ir.meta.anvil_version}`,
    ` */`,
    '',
    `import { z } from 'zod';`,
    '',
  ];

  for (const tool of ir.tools) {
    const schemaName = camelCase(tool.name) + 'InputSchema';
    lines.push(`export const ${schemaName} = z.object({`);
    for (const param of tool.parameters) {
      const schema = zodFieldType(param.field);
      const opt = param.required ? '' : '.optional()';
      const def = param.default_value !== undefined ? `.default(${JSON.stringify(param.default_value)})` : '';
      lines.push(`  ${param.name}: ${schema}${opt}${def},`);
    }
    lines.push('});');
    lines.push('');

    if (tool.returns && tool.returns.type === 'object') {
      const outSchema = camelCase(tool.name) + 'OutputSchema';
      lines.push(`export const ${outSchema} = z.object({`);
      for (const [key, prop] of Object.entries(tool.returns.properties)) {
        const opt = prop.required ? '' : '.optional()';
        lines.push(`  ${key}: ${zodFieldType(prop)}${opt},`);
      }
      lines.push('});');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generateClient(ir: AnvilIR, options: SdkTsOptions): string {
  const className = pascalCase(ir.service.name) + 'Client';
  const typeImports = ir.tools.map(t => {
    const names = [pascalCase(t.name) + 'Input'];
    if (t.returns) names.push(pascalCase(t.name) + 'Output');
    return names;
  }).flat().join(', ');

  const schemaImports = ir.tools.map(t => camelCase(t.name) + 'InputSchema').join(', ');

  const methods = ir.tools.map(tool => {
    const inputType = pascalCase(tool.name) + 'Input';
    const outputType = tool.returns ? pascalCase(tool.name) + 'Output' : 'void';
    const schemaName = camelCase(tool.name) + 'InputSchema';
    const methodName = camelCase(tool.name);

    return `
  /**
   * ${tool.description}
   *${tool.deprecated ? '\n   * @deprecated' + (tool.deprecation_message ? ` ${tool.deprecation_message}` : '') : ''}
   */
  async ${methodName}(input: ${inputType}): Promise<${outputType}> {
    const validated = ${schemaName}.parse(input);
    const response = await this.request('${tool.name}', validated);
    return response${tool.returns ? ` as ${outputType}` : ''};
  }`;
  }).join('\n');

  return `/**
 * ${ir.service.name} Client
 * Generated by Anvil v${ir.meta.anvil_version}
 */

import type { ${typeImports} } from './types.js';
import { ${schemaImports} } from './schemas.js';

export interface ${className}Options {
  baseUrl: string;
  apiKey?: string;
  headers?: Record<string, string>;
}

export class ${className} {
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(options: ${className}Options) {
    this.baseUrl = options.baseUrl.replace(/\\/$/, '');
    this.headers = {
      'Content-Type': 'application/json',
      ...options.headers,
    };
    if (options.apiKey) {
      this.headers['Authorization'] = \`Bearer \${options.apiKey}\`;
    }
  }

  private async request(tool: string, input: unknown): Promise<unknown> {
    const response = await fetch(\`\${this.baseUrl}/tools/\${tool}\`, {
      method: 'POST',
      headers: this.headers,
      body: JSON.stringify(input),
    });
    if (!response.ok) {
      const body = await response.text();
      throw new Error(\`\${tool} failed (\${response.status}): \${body}\`);
    }
    return response.json();
  }
${methods}
}
`;
}

// Helpers
function pascalCase(name: string): string {
  return name.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function camelCase(name: string): string {
  const pc = pascalCase(name);
  return pc.charAt(0).toLowerCase() + pc.slice(1);
}

function tsFieldType(f: AnvilField): string {
  switch (f.type) {
    case 'string': return 'string';
    case 'number': case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'enum': return f.values.map(v => typeof v === 'string' ? `'${v}'` : String(v)).join(' | ');
    case 'object': return tsObjectType(f);
    case 'array': return `${tsFieldType(f.items)}[]`;
    case 'union': return f.variants.map(v => tsFieldType(v)).join(' | ');
    default: return 'unknown';
  }
}

function tsObjectType(f: AnvilField): string {
  if (f.type !== 'object') return 'unknown';
  const props = Object.entries(f.properties).map(([key, prop]) => {
    const opt = prop.required ? '' : '?';
    return `  ${key}${opt}: ${tsFieldType(prop)};`;
  }).join('\n');
  return `{\n${props}\n}`;
}

function zodFieldType(f: AnvilField): string {
  switch (f.type) {
    case 'string': return 'z.string()';
    case 'number': return 'z.number()';
    case 'integer': return 'z.number().int()';
    case 'boolean': return 'z.boolean()';
    case 'enum': {
      const vals = f.values.map(v => JSON.stringify(v));
      return `z.enum([${vals.join(', ')}])`;
    }
    case 'array': return `z.array(${zodFieldType(f.items)})`;
    case 'object': {
      const props = Object.entries(f.properties).map(([k, v]) => `${k}: ${zodFieldType(v)}`).join(', ');
      return `z.object({ ${props} })`;
    }
    default: return 'z.unknown()';
  }
}
