/**
 * Anthropic/Claude API Target
 *
 * Generates tool definitions in the Anthropic Messages API format.
 * Output: JSON array of tool objects ready for the `tools` parameter.
 *
 * Format: https://docs.anthropic.com/en/docs/build-with-claude/tool-use
 */

import type { AnvilTarget, AnvilTargetFactory } from '@anvil-tools/compiler';
import type { AnvilIR } from '@anvil-tools/schema';
import { toolParametersToJsonSchema } from '@anvil-tools/schema';

export interface AnthropicTargetOptions {
  /** Include cache_control for prompt caching */
  cacheControl?: boolean;
}

export const anthropic: AnvilTargetFactory<AnthropicTargetOptions> = (options = {}) => ({
  name: 'anthropic',
  description: 'Generate Anthropic/Claude API tool definitions',
  primaryExtension: '.json',

  async generate(ir: AnvilIR) {
    const tools = ir.tools.map(tool => {
      const inputSchema = toolParametersToJsonSchema(tool);

      // Anthropic format: use agent description for better tool selection
      const def: Record<string, unknown> = {
        name: tool.name,
        description: tool.agent_description,
        input_schema: inputSchema,
      };

      if (options.cacheControl) {
        def['cache_control'] = { type: 'ephemeral' };
      }

      return def;
    });

    // Also generate a TypeScript file for easy integration
    const tsContent = generateTypeScript(ir, tools);

    return {
      target: 'anthropic',
      files: [
        {
          path: 'tools.json',
          content: JSON.stringify(tools, null, 2),
          type: 'schema' as const,
        },
        {
          path: 'tools.ts',
          content: tsContent,
          type: 'source' as const,
        },
      ],
    };
  },
});

function generateTypeScript(ir: AnvilIR, tools: Record<string, unknown>[]): string {
  return `/**
 * Anthropic Claude API tool definitions
 * Generated by Anvil v${ir.meta.anvil_version}
 *
 * Usage:
 *   import Anthropic from '@anthropic-ai/sdk';
 *   import { tools } from './tools.js';
 *
 *   const client = new Anthropic();
 *   const response = await client.messages.create({
 *     model: 'claude-opus-4-6',
 *     max_tokens: 16000,
 *     tools,
 *     messages: [{ role: 'user', content: '...' }],
 *   });
 */

import type Anthropic from '@anthropic-ai/sdk';

export const tools: Anthropic.Tool[] = ${JSON.stringify(tools, null, 2)};

export const toolNames = [${ir.tools.map(t => `'${t.name}'`).join(', ')}] as const;
export type ToolName = typeof toolNames[number];
`;
}
