/**
 * Documentation Generator
 *
 * Generates comprehensive Markdown documentation from Anvil IR.
 * Includes parameter tables, examples, agent metadata, permissions, and error docs.
 */

import type { AnvilIR, AnvilIRTool, AnvilIRParameter, AnvilField } from '@anvil-tools/schema';
import type { TargetResult, GeneratedFile } from '@anvil-tools/compiler';

export interface DocsOptions {
  format?: 'markdown' | 'html';
  singleFile?: boolean;
}

export function generateDocs(ir: AnvilIR, options: DocsOptions = {}): TargetResult {
  const singleFile = options.singleFile ?? (ir.tools.length <= 5);
  const files: GeneratedFile[] = [];

  if (singleFile) {
    files.push({
      path: 'README.md',
      content: generateSingleFile(ir),
      type: 'docs',
    });
  } else {
    files.push({
      path: 'README.md',
      content: generateIndex(ir),
      type: 'docs',
    });
    for (const tool of ir.tools) {
      files.push({
        path: `tools/${tool.name}.md`,
        content: generateToolDoc(tool, ir),
        type: 'docs',
      });
    }
  }

  return { target: 'docs', files };
}

function generateSingleFile(ir: AnvilIR): string {
  const lines: string[] = [];

  lines.push(`# ${ir.service.name}`);
  lines.push('');
  if (ir.service.description) {
    lines.push(ir.service.description);
    lines.push('');
  }
  lines.push(`> Generated by Anvil v${ir.meta.anvil_version}`);
  lines.push('');

  // Table of contents
  lines.push('## Tools');
  lines.push('');
  lines.push('| Tool | Description | Side Effects | Cost |');
  lines.push('|------|-------------|-------------|------|');
  for (const tool of ir.tools) {
    const dep = tool.deprecated ? ' *(deprecated)*' : '';
    lines.push(`| [\`${tool.name}\`](#${tool.name})${dep} | ${tool.description} | ${tool.side_effects} | ${tool.cost} |`);
  }
  lines.push('');

  // Each tool
  for (const tool of ir.tools) {
    lines.push('---');
    lines.push('');
    lines.push(renderTool(tool));
  }

  return lines.join('\n');
}

function generateIndex(ir: AnvilIR): string {
  const lines: string[] = [];

  lines.push(`# ${ir.service.name}`);
  lines.push('');
  if (ir.service.description) {
    lines.push(ir.service.description);
    lines.push('');
  }
  lines.push(`> Generated by Anvil v${ir.meta.anvil_version} | ${ir.tools.length} tools`);
  lines.push('');

  lines.push('## Tools');
  lines.push('');
  lines.push('| Tool | Description | Side Effects | Cost |');
  lines.push('|------|-------------|-------------|------|');
  for (const tool of ir.tools) {
    const dep = tool.deprecated ? ' *(deprecated)*' : '';
    lines.push(`| [\`${tool.name}\`](tools/${tool.name}.md)${dep} | ${tool.description} | ${tool.side_effects} | ${tool.cost} |`);
  }
  lines.push('');

  if (ir.service.base_url) {
    lines.push(`## Base URL`);
    lines.push('');
    lines.push(`\`${ir.service.base_url}\``);
    lines.push('');
  }

  if (ir.service.auth) {
    lines.push('## Authentication');
    lines.push('');
    lines.push(`Type: \`${ir.service.auth.type}\``);
    if (ir.service.auth.header) {
      lines.push(`Header: \`${ir.service.auth.header}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateToolDoc(tool: AnvilIRTool, ir: AnvilIR): string {
  return `# ${tool.name}\n\n${renderTool(tool)}\n\n---\n\n[Back to index](../README.md)\n`;
}

function renderTool(tool: AnvilIRTool): string {
  const lines: string[] = [];

  lines.push(`### \`${tool.name}\``);
  lines.push('');

  if (tool.deprecated) {
    lines.push(`> **Deprecated**${tool.deprecation_message ? `: ${tool.deprecation_message}` : ''}`);
    lines.push('');
  }

  lines.push(tool.description);
  lines.push('');

  // Metadata badges
  const badges: string[] = [];
  if (tool.side_effects !== 'none') badges.push(`Side Effects: **${tool.side_effects}**`);
  if (tool.cost !== 'free') badges.push(`Cost: **${tool.cost}**`);
  if (tool.idempotent) badges.push('Idempotent');
  if (tool.cache) badges.push(`Cached (${tool.cache.ttl}s)`);
  if (badges.length > 0) {
    lines.push(badges.join(' | '));
    lines.push('');
  }

  // Parameters
  if (tool.parameters.length > 0) {
    lines.push('#### Parameters');
    lines.push('');
    lines.push('| Name | Type | Required | Default | Description |');
    lines.push('|------|------|----------|---------|-------------|');
    for (const param of tool.parameters) {
      const typeStr = fieldTypeString(param.field);
      const def = param.default_value !== undefined ? `\`${JSON.stringify(param.default_value)}\`` : '—';
      const desc = param.field.description ?? '';
      lines.push(`| \`${param.name}\` | ${typeStr} | ${param.required ? 'Yes' : 'No'} | ${def} | ${desc} |`);
    }
    lines.push('');
  }

  // Returns
  if (tool.returns) {
    lines.push('#### Returns');
    lines.push('');
    lines.push(renderFieldType(tool.returns, 0));
    lines.push('');
  }

  // Errors
  if (tool.errors.length > 0) {
    lines.push('#### Errors');
    lines.push('');
    lines.push('| Code | Status | Message | Retryable |');
    lines.push('|------|--------|---------|-----------|');
    for (const err of tool.errors) {
      lines.push(`| \`${err.code ?? err.key}\` | ${err.status ?? '—'} | ${err.message} | ${err.retryable ? 'Yes' : 'No'} |`);
    }
    lines.push('');
  }

  // Permissions
  if (tool.permissions.length > 0) {
    lines.push('#### Permissions');
    lines.push('');
    for (const perm of tool.permissions) {
      const methods = perm.methods ? ` (${perm.methods.join(', ')})` : '';
      lines.push(`- **${perm.type}**: \`${perm.target}\`${methods}${perm.reason ? ` — ${perm.reason}` : ''}`);
    }
    lines.push('');
  }

  // Agent Metadata
  if (tool.when_to_use.length > 0 || tool.when_not_to_use.length > 0 || tool.tips.length > 0) {
    lines.push('#### Agent Guidance');
    lines.push('');
    if (tool.when_to_use.length > 0) {
      lines.push('**When to use:**');
      for (const w of tool.when_to_use) lines.push(`- ${w}`);
      lines.push('');
    }
    if (tool.when_not_to_use.length > 0) {
      lines.push('**When NOT to use:**');
      for (const w of tool.when_not_to_use) lines.push(`- ${w}`);
      lines.push('');
    }
    if (tool.tips.length > 0) {
      lines.push('**Tips:**');
      for (const t of tool.tips) lines.push(`- ${t}`);
      lines.push('');
    }
  }

  // Examples
  if (tool.examples.length > 0) {
    lines.push('#### Examples');
    lines.push('');
    for (const ex of tool.examples) {
      lines.push(`**${ex.name}**${ex.description ? ` — ${ex.description}` : ''}`);
      if (ex.prompt) {
        lines.push(`> Prompt: *"${ex.prompt}"*`);
      }
      lines.push('');
      lines.push('Input:');
      lines.push('```json');
      lines.push(JSON.stringify(ex.input, null, 2));
      lines.push('```');
      if (ex.output !== undefined) {
        lines.push('');
        lines.push('Output:');
        lines.push('```json');
        lines.push(JSON.stringify(ex.output, null, 2));
        lines.push('```');
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

function fieldTypeString(f: AnvilField): string {
  switch (f.type) {
    case 'enum': return `enum(${f.values.join(', ')})`;
    case 'array': return `${fieldTypeString(f.items)}[]`;
    case 'object': return 'object';
    case 'union': return f.variants.map(v => fieldTypeString(v)).join(' \\| ');
    default: return f.type;
  }
}

function renderFieldType(f: AnvilField, depth: number): string {
  if (f.type === 'object') {
    const lines: string[] = [];
    lines.push('| Field | Type | Description |');
    lines.push('|-------|------|-------------|');
    for (const [key, prop] of Object.entries(f.properties)) {
      lines.push(`| \`${key}\` | ${fieldTypeString(prop)} | ${prop.description ?? ''} |`);
    }
    return lines.join('\n');
  }
  return `Type: \`${fieldTypeString(f)}\`${f.description ? ` — ${f.description}` : ''}`;
}
