/**
 * MCP Server Generator (Production)
 *
 * Generates a fully functional MCP server using @modelcontextprotocol/sdk.
 * The output is a standalone TypeScript project that works out of the box
 * with Claude Desktop, Cursor, VS Code, and any MCP client.
 */

import type { AnvilIR, AnvilIRTool, AnvilField } from '@anvil-tools/schema';
import { toolParametersToJsonSchema } from '@anvil-tools/schema';
import type { TargetResult, GeneratedFile } from '@anvil-tools/compiler';

export interface McpOptions {
  transport?: 'stdio' | 'http';
  port?: number;
}

export function generateMcp(ir: AnvilIR, options: McpOptions = {}): TargetResult {
  const transport = options.transport ?? 'stdio';
  const port = options.port ?? 3000;
  const files: GeneratedFile[] = [];

  files.push({ path: 'server.ts', content: genServer(ir, transport, port), type: 'source' });
  files.push({ path: 'handlers.ts', content: genHandlers(ir), type: 'source' });
  files.push({ path: 'types.ts', content: genTypes(ir), type: 'source' });
  files.push({ path: 'env.ts', content: genEnvConfig(ir), type: 'source' });
  files.push({ path: 'GUIDE.md', content: genGuide(ir), type: 'docs' });
  files.push({ path: 'package.json', content: genPackageJson(ir), type: 'config' });
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
        strict: true, esModuleInterop: true, skipLibCheck: true,
        outDir: './dist', declaration: true, sourceMap: true,
      },
      include: ['*.ts'],
    }, null, 2),
    type: 'config',
  });

  return { target: 'mcp', files };
}

// ─── Server ─────────────────────────────────────────────────────────────────

function genServer(ir: AnvilIR, transport: string, port: number): string {
  const toolDefs = ir.tools.map(genToolDef).join(',\n    ');

  const handlerCases = ir.tools.map(t => {
    const fn = camel(t.name);
    const typeName = pascal(t.name) + 'Input';
    return `      case '${t.name}': {
        const input = (args ?? {}) as ${typeName};
        return await handlers.${fn}(input);
      }`;
  }).join('\n');

  const typeImports = ir.tools.map(t => pascal(t.name) + 'Input').join(', ');

  const transportCode = transport === 'stdio'
    ? `import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

const transport = new StdioServerTransport();
await server.connect(transport);
console.error('[${ir.service.name}] MCP server running on stdio');`
    : `import { SSEServerTransport } from '@modelcontextprotocol/sdk/server/sse.js';
import { createServer } from 'node:http';

const httpServer = createServer(async (req, res) => {
  if (req.method === 'GET' && req.url === '/sse') {
    const transport = new SSEServerTransport('/messages', res);
    await server.connect(transport);
  } else if (req.method === 'POST' && req.url === '/messages') {
    // Handle SSE message posting
  } else {
    res.writeHead(404);
    res.end('Not found');
  }
});

httpServer.listen(${port}, () => {
  console.error('[${ir.service.name}] MCP server running on http://localhost:${port}/sse');
});`;

  return `/**
 * ${ir.service.name} — MCP Server
 * Generated by Anvil v${ir.meta.anvil_version}
 *
 * ${ir.service.description}
 *
 * Usage:
 *   npm install && npm run build && npm start
 *   # or for development:
 *   npx tsx server.ts
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  type CallToolResult,
} from '@modelcontextprotocol/sdk/types.js';
import * as handlers from './handlers.js';
import type { ${typeImports} } from './types.js';

// ─── Server Setup ───────────────────────────────────────────────────────────

const server = new Server(
  { name: '${ir.service.name}', version: '${ir.service.version}' },
  { capabilities: { tools: {} } },
);

// ─── Tool List ──────────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    ${toolDefs}
  ],
}));

// ─── Tool Dispatch ──────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request): Promise<CallToolResult> => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
${handlerCases}
      default:
        return {
          content: [{ type: 'text', text: \`Unknown tool: \${name}\` }],
          isError: true,
        };
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      content: [{ type: 'text', text: \`Error in \${name}: \${message}\` }],
      isError: true,
    };
  }
});

// ─── Error Handling ─────────────────────────────────────────────────────────

server.onerror = (error) => {
  console.error('[${ir.service.name}] Server error:', error);
};

process.on('SIGINT', async () => {
  await server.close();
  process.exit(0);
});

// ─── Transport ──────────────────────────────────────────────────────────────

${transportCode}
`;
}

// ─── Tool Definition ────────────────────────────────────────────────────────

function genToolDef(tool: AnvilIRTool): string {
  const schema = toolParametersToJsonSchema(tool);

  const annotations: Record<string, unknown> = {};
  if (tool.side_effects === 'none' || tool.side_effects === 'read') annotations['readOnlyHint'] = true;
  if (tool.side_effects === 'destructive') annotations['destructiveHint'] = true;
  if (tool.idempotent) annotations['idempotentHint'] = true;
  annotations['openWorldHint'] = tool.side_effects !== 'none';

  const obj: Record<string, unknown> = {
    name: tool.name,
    description: tool.agent_description,
    inputSchema: schema,
    annotations,
  };

  return JSON.stringify(obj, null, 6).replace(/\n/g, '\n    ').replace(/^{/, '{').replace(/}$/, '    }');
}

// ─── Handlers ───────────────────────────────────────────────────────────────

function genHandlers(ir: AnvilIR): string {
  const handlers = ir.tools.map(tool => {
    const fn = camel(tool.name);
    const inputType = pascal(tool.name) + 'Input';

    // Generate example-based stub that returns real data when available
    let body: string;
    if (tool.examples.length > 0 && tool.examples[0]!.output) {
      const exOutput = JSON.stringify(tool.examples[0]!.output, null, 4);
      body = `  // Stub: returning example data. Replace with real implementation.
  const result = ${exOutput};
  return {
    content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
  };`;
    } else {
      body = `  // TODO: Implement ${tool.name}
  return {
    content: [{ type: 'text', text: JSON.stringify({ status: 'not_implemented', tool: '${tool.name}' }) }],
    isError: true,
  };`;
    }

    const doc = [
      `/**`,
      ` * ${tool.description}`,
      ...(tool.tips.length > 0 ? [` *`, ...tool.tips.map(t => ` * Tip: ${t}`)] : []),
      ` *`,
      ` * Side effects: ${tool.side_effects} | Cost: ${tool.cost} | Idempotent: ${tool.idempotent}`,
      ` */`,
    ].join('\n');

    return `${doc}
export async function ${fn}(input: ${inputType}): Promise<ToolResult> {
${body}
}`;
  }).join('\n\n');

  return `/**
 * Tool Handlers for ${ir.service.name}
 * Generated by Anvil v${ir.meta.anvil_version}
 *
 * Each handler receives typed input and returns an MCP CallToolResult.
 * Replace the stubs below with your actual implementation.
 */

import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import type { ${ir.tools.map(t => pascal(t.name) + 'Input').join(', ')} } from './types.js';

type ToolResult = CallToolResult;

${handlers}
`;
}

// ─── Types ──────────────────────────────────────────────────────────────────

function genTypes(ir: AnvilIR): string {
  const types = ir.tools.map(tool => {
    const inputName = pascal(tool.name) + 'Input';
    const props = tool.parameters.map(p => {
      const opt = p.required ? '' : '?';
      const doc = p.field.description ? `  /** ${p.field.description} */\n` : '';
      return `${doc}  ${p.name}${opt}: ${tsType(p.field)};`;
    }).join('\n');

    return `export interface ${inputName} {\n${props}\n}`;
  }).join('\n\n');

  return `/**
 * TypeScript types for ${ir.service.name} tool inputs
 * Generated by Anvil v${ir.meta.anvil_version}
 */

${types}
`;
}

// ─── Package.json ───────────────────────────────────────────────────────────

function genPackageJson(ir: AnvilIR): string {
  return JSON.stringify({
    name: `${ir.service.name}-mcp`,
    version: ir.service.version,
    description: `MCP server for ${ir.service.name} — generated by Anvil`,
    type: 'module',
    main: './dist/server.js',
    bin: { [ir.service.name]: './dist/server.js' },
    scripts: {
      build: 'tsc',
      start: 'node dist/server.js',
      dev: 'tsx server.ts',
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.12.0',
    },
    devDependencies: {
      typescript: '^5.8.0',
      tsx: '^4.0.0',
      '@types/node': '^22.0.0',
    },
  }, null, 2);
}

// ─── Helpers ────────────────────────────────────────────────────────────────

// ─── Env Config ─────────────────────────────────────────────────────────────

function genEnvConfig(ir: AnvilIR): string {
  const envVars: string[] = [];

  if (ir.service.auth?.env_var) {
    envVars.push(`/** ${ir.service.auth.type} authentication */\nexport const ${ir.service.auth.env_var} = env('${ir.service.auth.env_var}');`);
  }

  if (ir.service.base_url) {
    envVars.push(`/** Service base URL */\nexport const BASE_URL = env('BASE_URL', '${ir.service.base_url}');`);
  }

  return `/**
 * Environment configuration for ${ir.service.name}
 * Generated by Anvil v${ir.meta.anvil_version}
 */

function env(key: string, fallback?: string): string {
  const value = process.env[key] ?? fallback;
  if (!value) throw new Error(\`Missing required env var: \${key}\`);
  return value;
}

${envVars.length > 0 ? envVars.join('\n\n') : '// No environment variables required'}
`;
}

// ─── Guide ──────────────────────────────────────────────────────────────────

function genGuide(ir: AnvilIR): string {
  const firstTool = ir.tools[0];
  const fn = firstTool ? camel(firstTool.name) : 'myTool';
  const type = firstTool ? pascal(firstTool.name) + 'Input' : 'MyInput';

  return `# ${ir.service.name} MCP Server — Implementation Guide

Generated by Anvil. This guide explains how to implement your tool handlers.

## Quick Start

\`\`\`bash
npm install
npm run dev    # starts with tsx (hot reload)
\`\`\`

## How It Works

1. **server.ts** — MCP server setup + tool registration. Don't edit this.
2. **handlers.ts** — Your tool implementations. **Edit this file.**
3. **types.ts** — TypeScript interfaces for inputs. Auto-generated.
4. **env.ts** — Environment variable helpers.

## Writing a Handler

Each handler receives typed input and returns a \`CallToolResult\`:

\`\`\`typescript
// handlers.ts
import { BASE_URL } from './env.js';

export async function ${fn}(input: ${type}): Promise<ToolResult> {
  // 1. Call your API / database / service
  const response = await fetch(\`\${BASE_URL}/endpoint\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(input),
  });

  if (!response.ok) {
    // 2. Return errors with isError: true
    return {
      content: [{ type: 'text', text: \`API error: \${response.status}\` }],
      isError: true,
    };
  }

  const data = await response.json();

  // 3. Return results as text content
  return {
    content: [{ type: 'text', text: JSON.stringify(data, null, 2) }],
  };
}
\`\`\`

## Return Formats

\`\`\`typescript
// Text result
return { content: [{ type: 'text', text: 'Hello, World!' }] };

// JSON result
return { content: [{ type: 'text', text: JSON.stringify(data) }] };

// Error
return { content: [{ type: 'text', text: 'Something went wrong' }], isError: true };

// Image result
return { content: [{ type: 'image', data: base64String, mimeType: 'image/png' }] };
\`\`\`

## Connecting to Claude Desktop

\`\`\`json
{
  "mcpServers": {
    "${ir.service.name}": {
      "command": "node",
      "args": ["${process.cwd()}/out/mcp/dist/server.js"]
    }
  }
}
\`\`\`

Save to \`~/Library/Application Support/Claude/claude_desktop_config.json\` (macOS)
or \`%APPDATA%/Claude/claude_desktop_config.json\` (Windows).

## Connecting to Cursor

Add to \`.cursor/mcp.json\` in your project:

\`\`\`json
{
  "mcpServers": {
    "${ir.service.name}": {
      "command": "node",
      "args": ["./out/mcp/dist/server.js"]
    }
  }
}
\`\`\`

## Building for Production

\`\`\`bash
npm run build
npm start
\`\`\`
`;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function camel(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function pascal(name: string): string {
  return name.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function tsType(f: AnvilField): string {
  switch (f.type) {
    case 'string': return 'string';
    case 'number': case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'enum': return f.values.map(v => typeof v === 'string' ? `'${v}'` : String(v)).join(' | ');
    case 'object': {
      const props = Object.entries(f.properties).map(([k, v]) =>
        `${k}${v.required ? '' : '?'}: ${tsType(v)}`
      ).join('; ');
      return `{ ${props} }`;
    }
    case 'array': return `${tsType(f.items)}[]`;
    default: return 'unknown';
  }
}
