/**
 * CLI Generator
 *
 * Generates a commander-based CLI application from Anvil IR.
 * Each tool becomes a subcommand with flags derived from parameters.
 */

import type { AnvilIR, AnvilIRTool, AnvilField } from '@anvil-tools/schema';
import type { TargetResult, GeneratedFile } from '@anvil-tools/compiler';

export interface CliGenOptions {}

export function generateCliGen(ir: AnvilIR, _options: CliGenOptions = {}): TargetResult {
  const files: GeneratedFile[] = [];

  files.push({
    path: 'cli.ts',
    content: generateCliFile(ir),
    type: 'source',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: `${ir.service.name}-cli`,
      version: ir.service.version,
      description: `CLI for ${ir.service.name} — generated by Anvil`,
      type: 'module',
      bin: { [ir.service.name]: './dist/cli.js' },
      scripts: { build: 'tsc', start: 'node dist/cli.js' },
      dependencies: { commander: '^13.1.0' },
      devDependencies: { typescript: '^5.8.0' },
    }, null, 2),
    type: 'config',
  });

  return { target: 'cli-gen', files };
}

function generateCliFile(ir: AnvilIR): string {
  const commands = ir.tools.map(tool => generateCommand(tool)).join('\n');

  return `#!/usr/bin/env node
/**
 * ${ir.service.name} CLI
 * Generated by Anvil v${ir.meta.anvil_version}
 */

import { Command } from 'commander';

const program = new Command()
  .name('${ir.service.name}')
  .version('${ir.service.version}')
  .description('${ir.service.description ?? ir.service.name}');

${commands}

program.parse();
`;
}

function generateCommand(tool: AnvilIRTool): string {
  const cmdName = tool.name.replace(/_/g, '-');
  const lines: string[] = [];

  lines.push(`program`);
  lines.push(`  .command('${cmdName}')`);
  lines.push(`  .description('${escapeQuote(tool.description)}')`);

  for (const param of tool.parameters) {
    const flag = toKebab(param.name);
    const typeHint = cliTypeHint(param.field);

    if (param.required) {
      lines.push(`  .requiredOption('--${flag} ${typeHint}', '${escapeQuote(param.field.description ?? param.name)}')`);
    } else {
      const def = param.default_value !== undefined ? `, ${JSON.stringify(param.default_value)}` : '';
      lines.push(`  .option('--${flag} ${typeHint}', '${escapeQuote(param.field.description ?? param.name)}'${def})`);
    }
  }

  lines.push(`  .option('--json', 'Output raw JSON')`);
  lines.push(`  .action(async (opts) => {`);
  lines.push(`    // TODO: Implement ${tool.name}`);
  lines.push(`    const result = { tool: '${tool.name}', args: opts };`);
  lines.push(`    if (opts.json) {`);
  lines.push(`      console.log(JSON.stringify(result, null, 2));`);
  lines.push(`    } else {`);
  lines.push(`      console.log(result);`);
  lines.push(`    }`);
  lines.push(`  });`);

  return lines.join('\n');
}

function toKebab(name: string): string {
  return name.replace(/_/g, '-');
}

function cliTypeHint(f: AnvilField): string {
  switch (f.type) {
    case 'string': return '<string>';
    case 'number': case 'integer': return '<number>';
    case 'boolean': return '';
    case 'enum': return `<${f.values.join('|')}>`;
    default: return '<value>';
  }
}

function escapeQuote(s: string): string {
  return s.replace(/'/g, "\\'");
}
