/**
 * Vercel AI SDK Target
 *
 * Generates tool definitions for the Vercel AI SDK (ai package).
 * Output: TypeScript file using the `tool()` helper from 'ai'.
 *
 * Format: tool({ description, parameters: z.object({...}), execute })
 */

import type { AnvilTarget, AnvilTargetFactory } from '@anvil-tools/compiler';
import type { AnvilIR, AnvilField } from '@anvil-tools/schema';

export interface VercelAITargetOptions {}

export const vercelAI: AnvilTargetFactory<VercelAITargetOptions> = (options = {}) => ({
  name: 'vercel-ai',
  description: 'Generate Vercel AI SDK tool definitions',
  primaryExtension: '.ts',

  async generate(ir: AnvilIR) {
    const toolDefs = ir.tools.map(tool => {
      const params = tool.parameters.map(p => {
        const zodType = fieldToZodString(p.field);
        const opt = p.required ? '' : '.optional()';
        const def = p.default_value !== undefined ? `.default(${JSON.stringify(p.default_value)})` : '';
        const desc = p.field.description ? `.describe(${JSON.stringify(p.field.description)})` : '';
        return `    ${p.name}: z.${zodType}${desc}${opt}${def},`;
      }).join('\n');

      return `  ${toCamelCase(tool.name)}: tool({
    description: ${JSON.stringify(tool.agent_description)},
    parameters: z.object({
${params}
    }),
    execute: async (args) => {
      // TODO: Implement ${tool.name}
      throw new Error('${tool.name} not implemented');
    },
  }),`;
    }).join('\n\n');

    const content = `/**
 * Vercel AI SDK tool definitions for ${ir.service.name}
 * Generated by Anvil v${ir.meta.anvil_version}
 *
 * Usage:
 *   import { generateText } from 'ai';
 *   import { anthropic } from '@ai-sdk/anthropic';
 *   import { tools } from './tools.js';
 *
 *   const result = await generateText({
 *     model: anthropic('claude-opus-4-6'),
 *     tools,
 *     prompt: 'What is the weather in SF?',
 *   });
 */

import { tool } from 'ai';
import { z } from 'zod';

export const tools = {
${toolDefs}
};
`;

    return {
      target: 'vercel-ai',
      files: [
        { path: 'tools.ts', content, type: 'source' as const },
      ],
    };
  },
});

function fieldToZodString(f: AnvilField): string {
  switch (f.type) {
    case 'string': return 'string()';
    case 'number': return 'number()';
    case 'integer': return 'number().int()';
    case 'boolean': return 'boolean()';
    case 'enum': return `enum([${f.values.map(v => JSON.stringify(v)).join(', ')}])`;
    case 'array': return `array(z.${fieldToZodString(f.items)})`;
    default: return 'unknown()';
  }
}

function toCamelCase(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
